import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Login.module.css";
import Link from "next/link";
import { useDispatch, useSelector } from "react-redux";
import { checkAuth, logout, mainSlice } from "@/store/mainSlice";
import { useEffect } from "react";

import { useRouter } from "next/router";

export default function Home() {
  const { push } = useRouter();
  const dispatch = useDispatch();
  const { category, user, isAuth } = useSelector((state: any) => state.mainReducer);
  const { changeIsAuth } = mainSlice.actions;
  const logoutUser = () => {
    dispatch(logout());
    // console.log(isAuth);
  };
  // artem.kuskin@progforce.com

  // useEffect(() => {
  //   const isCheckAuth = () => {
  //     if (localStorage.getItem("token")) {
  //       dispatch(checkAuth());
  //     }
  //   };
  //   isCheckAuth();
  //   if (!isAuth) {
  //     push("/");
  //   }
  // }, []);

  const onSubmint = (event) => {
    event.preventDefault();
    const response = dispatch(logout());
    if (response) {
      push("/");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={onSubmint}>
        <button type="submit" className={styles.link}>
          Logout
        </button>
        <h1>{user?.isactivated ? "Акк подтверден по почте" : "Подтвердите Аккаунт"}</h1>
      </form>
    </>
  );
}
