import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Login.module.css";
import Link from "next/link";
import { useDispatch, useSelector } from "react-redux";
import { checkAuth, logout, mainSlice } from "@/store/mainSlice";
import { useEffect } from "react";

import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const dispatch = useDispatch();
  const { category, users, isAuth } = useSelector((state: any) => state.mainReducer);
  const { changeIsAuth } = mainSlice.actions;
  const logoutUser = () => {
    dispatch(logout());
    // console.log(isAuth);
  };
  // artem.kuskin@progforce.com

  useEffect(() => {
    if (localStorage.getItem("token")) {
      dispatch(checkAuth());
    }
  }, []);

  // if (!isAuth) {
  //   return router.push("/login");
  // }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button>
        <Link onClick={() => logoutUser()} className={styles.link} href={isAuth ? `/` : `/login`}>
          Logout
        </Link>
        <h1>{users?.isActivated ? "Акк подтверден по почте" : "Подтвердите Аккаунт"}</h1>
      </button>
    </>
  );
}
