import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Login.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.background}`}>
        <div className={styles.loginForm}>
          <div className={styles.inputs}>
            <div className={styles.input}>
              <label>Email</label>
              <input></input>
            </div>
            <div className={styles.inputBlock}>
              <label>Password</label>
              <input></input>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
