import Head from "next/head";
import styles from "@/styles/Login.module.css";
import Link from "next/link";
import { useDispatch, useSelector } from "react-redux";
import { login, mainSlice, registration } from "@/store/mainSlice";
import { useState } from "react";

export default function Login() {
  const [email, setEmail] = useState();
  const [password, setPassword] = useState();
  const dispatch = useDispatch();
  const { category, users, isAuth } = useSelector(
    (state: any) => state.mainReducer
  );


  const loginUser = () => {
    dispatch(login({ email, password }));
    console.log(users);
  };

  const registrUser = () => {
    dispatch(registration({ email, password }));
    console.log(users);
  };

  const changeEmailInput = (email: string) => {
    setEmail(email);
    console.log(email);
  };

  const changePasswordInput = (password: string) => {
    setPassword(password);
  };


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.boll}></div>
      <main className={`${styles.background}`}>
        <div className={styles.loginForm}>
          <div className={styles.inputs}>
            <div className={styles.inputBlock}>
              <label>Email:*</label>
              <input
                onChange={(e) => changeEmailInput(e.target.value)}
                value={email}
              />
            </div>
            <div className={styles.inputBlock}>
              <label>Password:*</label>
              <input
                onChange={(e) => changePasswordInput(e.target.value)}
                value={password}
              />
            </div>
            <div className={styles.loginButtons}>
              <a>Registration</a>
              <button>
                <Link
                  onClick={() => loginUser()}
                  className={styles.link}
                  href={isAuth ? `/` : `/login`}
                >
                  Login
                </Link>
              </button>
              <Link
                onClick={() => registrUser()}
                className={styles.link}
                href={isAuth ? `/` : `/login`}
              >
                Forgot password?
              </Link>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
